### ISSUE TITLE
Line 2.2 in v0.55

### ISSUE THREAD

**Issue by JohnN6** [OddLingo/js8map#6]
Is this right - Line 202  ?
  elif c == 'INFO':
    sfr.info = js8['TEXT']
    print('{} info {}'.format(sfr.call, s.info))

The s.info throws an error ... should it be sfr.info   ?

Exxception in Tkinter callback
Traceback (most recent call last):
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/Users/johnnewgas/Documents/Py Scripts/js8map5d5/js8map.py", line 240, in check_messages
    do_cmd(js8)
  File "/Users/johnnewgas/Documents/Py Scripts/js8map5d5/js8map.py", line 202, in do_cmd
    print('{} info {}'.format(sfr.call, s.info))
NameError: name 's' is not defined

**Comment by OddLingo** [comment]
Processing of TEXT attributes has been cleaned up in version 0.55.
